source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
static_dir: assets
sass:
  sass_dir: _sass
  style: expanded 
repository: IceWaterNotIce/Protect-the-Earth
collections:
  plots:
    output: true
  games:
    output: true
